blogProject/blogApp/urls.py
from django.urls import path,re_path
from . import views

app_name='blogApp'

urlpatterns = [
    path('', views.post_list_view),
    re_path(r'^tag/(?P<tag_slug>[-\w]+)/$',views.post_list_view,name='post_list_by_tag_name'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',views.post_detail_view,name='post_detail'),
    re_path(r'^(?P<id>\d+)/share/$',views.mail_send_view,),
]

blogProject/blogProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogApp.urls',namespace='blogApp')),
    #path('', include('blogApp.urls')),
]

blogProject/blogApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.
class CustomManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES={('draft','Draft'),('published','Published')}
    title=models.CharField(max_length=264)
    slug=models.SlugField(max_length=264,unique_for_date='publish')
    author=models.ForeignKey(User,related_name='blog_posts',on_delete=models.CASCADE)
    body=models.TextField()
    publish=models.DateTimeField(default=timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    objects=CustomManager()
    tags=TaggableManager()

    class Meta:
        ordering=('-publish',)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blogApp:post_detail",args=[self.publish.year,self.publish.strftime('%m'),self.publish.strftime('%d'),self.slug])

class Comment(models.Model):
    post=models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    name=models.CharField(max_length=30)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)
    class Meta:
        ordering=('created',)
    def __str__(self):
        return 'Commented by {} on {}'.format(self.name,self.post)

blogProject/blogApp/forms.py
from django import forms
from blogApp.models import Comment
class EmailSendForm(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('name','email','body')

blogProject/blogApp/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blogApp.models import Post
from django.core.mail import send_mail
from blogApp.forms import EmailSendForm
from taggit.models import Tag
from blogApp.forms import CommentForm
# Create your views here.
def post_list_view(request):
    post_list=Post.objects.all()
    return render(request,'blogApp/post_list.html',{'post_list':post_list})

def post_detail_view(request,year,month,day,post):
    post=get_object_or_404(Post,slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    comments=post.comments.filter(active=True)
    csubmit=False
    if request.method=='POST':
        form=CommentForm(data=request.POST)
        if form.is_valid():
            new_comment=form.save(commit=False)
            new_comment.post=post
            new_comment.save()
            csubmit=True
    else:
        form=CommentForm()
    return render(request,'blogApp/post_detail.html',{'post':post,'form':form,'comments':comments,'csubmit':csubmit})

def post_list_view(request,tag_slug=None):
    post_list=Post.objects.all()
    tag=None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        post_list=post_list.filter(tags__in=[tag])

    paginator=Paginator(post_list,2)
    page_number=request.GET.get('page')
    try:
        post_list=paginator.page(page_number)
    except PageNotAnInteger:
        post_list=paginator.page(1)
    except EmptyPage:
        post_list=paginator.page(paginator.num_pages)
    return render(request,'blogApp/post_list.html',{'post_list':post_list})

def mail_send_view(request,id):
    post=get_object_or_404(Post,id=id,status='published')
    sent=False
    form=EmailSendForm(request.POST)
    if request.method=='POST':
        if form.is_valid():
            cd=form.cleaned_data
            post_url=request.build_absolute_uri(post.get_absolute_url())
            subject='{}({}) recommends you to read "{}"'.format(cd['name'],cd['email'],post.title)
            message='Read Post At:\n{}\n{}\' comments:\n{}'.format(post_url,cd['name'],cd['comments'])
            send_mail(subject,message,'jacksonmama0505@gmail.com',[cd['to']])
            sent=True
        else:
            form=EmailSendForm()
    return render(request,'blogApp/sharebymail.html',{'post':post,'form':form,'sent':sent})

blogProject/templates/blogApp/base.html
<!DOCTYPE html>
{%load blog_tags%}
{%load staticfiles%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{%static "css/blog.css"%}">
    <title>{%block title%}{%endblock%}</title>
  </head>
  <body>
    <div class="content">
      {%block content%}{%endblock%}
    </div>
    <div class="sidebar">
      <h2>JOSEPH BLOG</h2>
      <p>The total number of published posts upto today:<span id="pcount">{%total_posts%}</span></p>
      <h3>LATEST POSTS:</h3>{%show_latest_posts%}
      </ul>
    </div>
  </body>
</html>

blogProject/templates/blogApp/latest_posts123.html
<ul>
  {%for post in latest_posts%}
  <p id='po'><li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li></p>
  {%endfor%}
</ul>

blogProject/templates/blogApp/pagination.html
<div class="paginator">
  <span>
     {%if page.has_previous%}
       <a href="?page={{page.previous_page_number }}">Previous</a>&nbsp&nbsp&nbsp
     {%endif%}
    <span class='current'>
      page{{page.number}} of {{page.paginator.num_pages}}&nbsp&nbsp&nbsp
    </span>
     {%if page.has_next%}
      <a href="?page={{page.next_page_number}}">Next</a>&nbsp&nbsp&nbsp
    {%endif%}
  </span>
</div>

blogProject/templates/blogApp/post_detail.html
<!DOCTYPE html>
{%extends 'blogApp/base.html'%}
{%block title%}{{post.title}}{%endblock%}
{%block content%}
    <h1>{{post.title}}</h1>
    <p id="date">Published on {{post.publish}} by {{post.author|title}}</p>
    {{post.body|linebreaks}}
    <a href="/{{post.id}}/share" class="btn btn-lg btn-primary">Share Post By Email</a>
    {% with comments.count as comments_count %}
    <h2>{{comments_count}} Comment{{comments_count|pluralize}}</h2>
    {%endwith%}
    {%if comments %}
      {%for comment in comments%}
       <p id='dab'>comment {{forloop.counter}} by {{comment.name}} on {{comment.created}}</p>
       <div class="cb">
         {{comment.body|linebreaks}}
       </div>
       <hr>
      {%endfor%}
    {%else%}
      <p>There are no Comments</p>
    {%endif%}
    {%if csubmit%}
      <h2>Your Comment Added successfully</h2>
      {%else%}
      <form method="post">
        {{form.as_p}}
        {%csrf_token%}
        <input type="submit" class="btn btn-lg btn-primary" value="Submit Comment">
      </form>
    {%endif%}
{%endblock%}

blogProject/templates/blogApp/post_list.html
<!DOCTYPE html>
{%extends 'blogApp/base.html'%}
{%block title%}JOSEPH 'S BLOG HOMEPAGE{%endblock%}
{%block content%}
<h1>WELCOME TO JOSEPH BLOG</h1>
{%if tag%}
<h2>Posts tagged with "{{tag.name}}"</h2>
{%endif%}
{%for post in post_list%}
  <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
  <p>Tags:
    {%for tag in post.tags.all%}
     <a href="{%url "blogApp:post_list_by_tag_name" tag.slug%}" class="btn btn-lg btn-success">{{tag.name}}</a>
    {%endfor%}
  </p>
  <p id="date">Published on {{post.publish}} by {{post.author|title}}</p>
  {{post.body|truncatewords:40|linebreaks}}
{%endfor%}
{%include 'blogApp/pagination.html' with page=post_list%}
{%endblock%}

blogProject/templates/blogApp/sharebymail.html
<!DOCTYPE html>
{%extends 'blogApp/base.html'%}
{% block title %}Share Post By Email{% endblock %}
{%block content%}
  {%if sent%}
    <h1>Email sent successfully..!!</h1>
    <h2>"{{post.title}}" was sent by email</h2>
  {%else%}
      <h1>Share {{post.title}}" by Email!!"</h1>
      <form method="post">
        {{form.as_p}}
        {%csrf_token%}
        <input type="submit" name="" class='btn btn-lg btn-success' value="Send Mail">
      </form>>
  {%endif%}
{%endblock%}